server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acquisto_azioni
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    date-format: yyyyMMdd
    serialization:
      write-dates-as-timestamps: false

flyway:
  enabled: true
  locations: classpath:db/migration
